restore positional params, sanitize input, fix var

diff --git a/cyborg-create b/cyborg-create
--- a/cyborg-create
+++ b/cyborg-create
@@ -72,6 +72,21 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
+# restore positional params
+set -- "${_POSITIONAL[@]}"
+
+if ! [[ ${#_POSITIONAL[@]} -ge 1 ]]; then
+  echo 'Sorry, missing borg archive name. Please supply name.'
+  _usage
+  exit 1
+fi
+
+if ! [[ ${#_POSITIONAL[@]} -ge 2 ]]; then
+  echo 'Sorry, missing path(s) for archival. Please supply path(s).'
+  _usage
+  exit 1
+fi
+
 if [[ -z "$BORG_REPO" ]]; then
   echo 'Sorry, missing $BORG_REPO environment variable. Please export it.'
   _usage
@@ -98,7 +113,7 @@ borg_create() {
   local _paths_for_archival
 
   _args="$@"
-  _archive_name="${_args[0]}"
+  _archive_name="$1"
   _paths_for_archival="${_args[@]:1}"
 
   # be communicative
